### ISSUE TITLE
Install plugin using ssh interface as root

### ISSUE THREAD

**Issue by danilokleber** [michaelshobbs/dokku-ecr-login#2]
Hey, how can I install this plugin using a ssh interface? I'm using GitLab CI to automate my Dokku review apps deployment. The line for the installation is:

`ssh dokku@ssh.domain plugin:install https://github.com/michaelshobbs/dokku-ecr-login.git`

I found that plugins need to be installed as root though I tried adding `sudo` with no success.  Sorry if this is a newbie question.

**Comment by michaelshobbs** [comment]
This plugin does not require root privileges. However, if other plugins' `install` triggers do, the installation process will certainly fail. I'm not sure plugin installation via SSH is necessarily supported but please feel free to open an issue against dokku/dokku or jump on the gliderlabs community slack. 

https://glider-slackin.herokuapp.com/

**Comment by danilokleber** [comment]
I'm not using any other plugins and I think installation via SSH is supported because I get the following error message: `This command must be run as root`.
